// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"geek-time/week4/interface"
	"geek-time/week4/interface/v1"
	"geek-time/week4/internal/domain/hello_domain"
	"geek-time/week4/internal/infrastructure/hello_infrastructure"
	"geek-time/week4/pkg/application/hello_application"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InjectRouters() *gin.Engine {
	hello := v1.NewHello()
	engine := routers.NewRouter(hello)
	return engine
}

func InjectApplication() hello_application.Application {
	db := hello_infrastructure.NewDB()
	domain := hello_domain.NewDomain(db)
	application := hello_application.NewApplication(domain)
	return application
}

// wire.go:

var applicationProviderSet = wire.NewSet(hello_application.NewApplication, hello_domain.NewDomain, hello_infrastructure.NewDB)
